const datosDeTestimonios = [
    {
        id: 1,
        nombre: "Profesor Tomas Naranjo Flores",
        info: "El ciclón que devastó Minatitlán en octubre de 1959 dejó una huella imborrable en la memoria de sus habitantes. Conocido como Linda, el fenómeno comenzó a manifestarse el 22 de octubre, pero alcanzó su apogeo el 27, cuando vientos feroces y lluvias torrenciales azotaron la comunidad. El caos fue indescriptible. A medida que el ciclón avanzaba, árboles centenarios caían, techos eran arrancados y el estruendo era similar al de un tren. La tierra temblaba bajo la furia de la tormenta. Las familias, desbordadas por el desastre, se vieron arrastradas hacia el cauce del río Marabasco, perdiendo no solo sus hogares, sino a seres queridos en el proceso.La comunidad, que alguna vez fue un lugar de juegos y risas, se convirtió en un desierto de escombros. En medio del horror, surgieron actos de valentía, como el llamado de Apolodoro Mancilla Figueroa a los que aún podían salvarse.Tras la tormenta, aquellos que sobrevivieron enfrentaron el difícil camino de la recuperación. Las pérdidas fueron profundas, y el recuerdo de aquellos que se fueron persiste, conmemorados en corridos que evocan su memoria y el deseo de que algo así nunca vuelva a suceder. La resiliencia de Minatitlán se forjó en la adversidad, recordando siempre a los caídos en aquella fatídica mañana.",
        foto: "tomas-naranjo.png"
    },

    {
        id: 2,
        nombre: "Francisco Serratos Figueroa",
        info: "El 27 de octubre de 1959, un ciclón devastador azotó el municipio de Minatitlán Colima, dejando destrucción y sufrimiento. Este informe presenta un relato personal de los eventos que ocurrieron después de la tragedia, basado en la experiencia del testigo llamado Francisco Serratos Figueroa que en su momento tenía 11 años de edad. El día en el que ocurrieron los hechos se escuchaba un fuerte sonido del viento y demasiada lluvia causando que cayeran grandes cantidades de agua y lodo a la parte que hoy conocemos como el jardín, al terminar el ciclón nos cuenta que hubo escasez de comida y ropa ya que todo estaba sepultado por lodo, debido a que no había forma de llegar al municipio los helicópteros traían la comida así como también medicinas que eran entregadas mediante paracaídas para las personas afectadas, así mismo también llegaban aviones que recogían heridos, ya que esto causó que personas fallecieran, salieran heridas y algunas quedarán sepultadas en la tierra, en ese momento personas de las rancherías y de Colima se sumaron para ayudar a las personas, nos cuenta que algunas personas eran encontradas muertas y las personas apoyaban para poder sepultar los cuerpos. También había puntos que servían de ayuda como 3 casa que quedaron en pie en donde hoy es el centro de Minatitlán, hay se atendían a las personas y también se les recogía en aviones a las que estaban heridas, también en donde hoy es la carnicería de los palacios se hizo un cuartel donde se otorgaba comida las personas según el número de integrantes que había por familia, que en palabras de nuestro testigo era una buena despensa que estaba conformada principalmente por arroz, frijol, leche y jabón. También se nos cuenta que en ese momento reporteros llegaron a Minatitlán donde tomaron fotografías y tomaron testimonio de los hechos ocurridos, también llegaron personas que formaban parte del gobierno de Colima y ellos aterrizaron donde hoy es la colonia santa Teresita. Nos cuenta que el no sufrió daños gracias a que se dirigía a llevar nixtamal al centro del pueblo a donde hoy es la caja popular ya que hay era el molino del pueblo, pero por las fuertes lluvias fue llegó a casa de su tío a moler el nixtamal, ya que tenía un un molino gracias a eso no le pasó nada por qué lo que hoy conocemos como el jardín y la iglesia fueron sepultados en lodo",
        foto: "francisco-serratos-figueroa.jpeg",
    },

    {
        id: 3,
        nombre: "Esther Quiñonez Meza",
        info: "Esther Quiñonez Meza narra su experiencia con el ciclón que devastó Minatitlán en 1959, un evento que dejó una marca indeleble en su vida. Recuerda cómo, al principio, la lluvia parecía una tormenta común, pero pronto se convirtió en un huracán implacable. Los vientos arremetieron con tal fuerza que las casas comenzaron a ceder, y el agua se coló en los hogares, obligando a las familias a buscar refugio. El momento más aterrador llegó cuando el río se desbordó, arrastrando no solo bienes materiales, sino también las esperanzas y sueños de la comunidad. En medio del caos, la gente se unió para enfrentar la adversidad, ayudándose mutuamente en un acto de solidaridad. Los niños eran consolados mientras los adultos lidiaban con su propio miedo. Al amainar la tormenta, se encontraron con un paisaje de destrucción; Minatitlán era irreconocible. Los días siguientes fueron difíciles, con la ayuda que tardaba en llegar y la necesidad de reconstruir desde cero. Aquellos que perdieron sus hogares fueron acogidos por familiares, y juntos comenzaron el arduo proceso de limpieza y restauración. A medida que el pueblo se levantaba de sus cenizas, la experiencia dejó una huella emocional profunda en todos los que vivieron aquella tragedia. La resiliencia se convirtió en una lección valiosa, recordándoles lo frágil y preciosa que es la vida. Aunque muchos decidieron irse, los que se quedaron lo hicieron porque Minatitlán era su hogar. Con el tiempo, las casas fueron reconstruidas y los cultivos replantados, pero el trauma permaneció en la memoria colectiva. Esther reflexiona sobre cómo, al caminar por el pueblo, puede ver las huellas invisibles de aquel evento. La tragedia transformó su percepción de la vida, haciéndola valorar el apoyo entre vecinos y el amor por la tierra. La experiencia les enseñó que, a pesar de sus esfuerzos, la naturaleza tiene una fuerza que puede cambiarlo todo en un instante. La frase final encapsula su aprendizaje: “La vida es un soplo frágil, y el verdadero valor está en quienes nos rodean cuando el viento arrasa lo demás.",
        foto: "esther-quinonez-meza.jpeg",
    },

    {
        id: 4,
        nombre: "Héctor Manuel Mancilla Figueroa",
        info: "Héctor Manuel Mancilla Figueroa, un ilustre profesor y ex director del bachillerato 11, rememora con 90 años la trágica experiencia del ciclón que devastó Minatitlán cuando él tenía 25 años. En sus palabras, relata que el clima ya había comenzado a deteriorarse una semana antes del evento, con lluvias intensas que se intensificaron la noche anterior al desastre. En la madrugada, alrededor de las 12 a.m., la lluvia se volvió torrencial, y entre las 4 y 5 a.m., el ciclón azotó con una fuerza implacable. Al amanecer, Héctor decidió salir a la calle, vistiendo su chila (un impermeable de palma), para evaluar los daños en su comunidad. Al caminar por la calle Mártires del Tacamo, notó que la lluvia continuaba y las gotas eran increíblemente gruesas y pesadas. Al llegar a la escuela primaria donde trabajaba, tomó la difícil decisión de suspender las clases por el peligro inminente. Sin embargo, lo que siguió fue devastador: un desprendimiento de tierra masivo arrastró una pequeña casa, y ese mismo alud destruyó la presidencia municipal, ubicada donde hoy se encuentra la casa de la cultura. También se llevaron consigo el juzgado y el cuartel de seguridad del municipio. Lleno de pánico, Héctor recordó que la iglesia del pueblo tenía una cimentación sólida, así que corrió hacia ella en busca de refugio. Al entrar, se subió a la cornisa y se sujetó de una ventana, observando cómo su hermoso pueblo quedaba arrasado. La colonia más importante, donde actualmente se encuentra el sindicato minero, fue completamente destruida. Después de un tiempo, cuando finalmente el derrumbe se detuvo, Héctor logró salir de la iglesia. Su primer instinto fue buscar a su familia, pero se encontró con una escena desgarradora: cadáveres esparcidos y varias personas heridas. Entre estos, vio a una niña de 5 años, Yolanda Larios Montes de Oca. Sin dudarlo, decidió ayudarla. Continuando su camino, Héctor llevó a los heridos a la casa de la familia Figueroa, una de las más influyentes del municipio. Su testimonio es un recordatorio conmovedor de la devastación que dejó el ciclón y la resiliencia de aquellos que sobrevivieron a la tragedia.",
        foto: "hector-mancilla-figueroa.jpeg"
    }


];

testimonioId = window.location.search.split("=")[1]

const testimonioInfo = datosDeTestimonios.find((testimonio) => testimonio.id == testimonioId)


let testimonioTexto = document.getElementById("testimonio").innerText = testimonioInfo.info
let testimonioTitulo = `Testimonio de ${document.getElementById("titulo").innerText = testimonioInfo.nombre}`

let testimonioImg = document.getElementById("imagen").setAttribute(`src`, `img/personas/${testimonioInfo.foto}`)